### PR TITLE
#4 Divergence protocol initial implementation

### PR DESCRIPTION
**Pull request by Kyjaque**
Use run.py, to run the simulations, it is outside of main directory, it should open browser windows with charts

adding/fixing:
- simulation of trade functions
- buyback tax
- pool distribution
- arbitrage
- plotting

### CODE REVIEW

**Comment by RedlineDrifter** [comment]
strategy.py -- check line 62

**Comment by Kyjaque** [comment]
### Simple usage 
Minimum code to run sims and display results:

1. get simulated functions (predefined)
sims = simulationSamples(42, False, 365 * 6 * 2)
alternative is your own dictionary in the format of. key is the name of the function, data is array of floats (prices), timeframe in seconds
prices={"wild brownian": {"data": X, "timeframe": timeframe}, ...}
2. pick simulation divergence parameters
div_protocol_args = {
    "soft_peg_price": ust_start_price,  # start right at the peg price, seems a smart decision
    # after we reach final peg 1$, this ratio of tax is left for arb traders to keep. 0 = we tax 100% of divergence
    "arbitrage_coef": 0.05, # when at peg $1, we tax this ratio less to allow arbitrage
    "cex_tax_coef": 0.001,  # ratio of how much tax CEX gets
    # not used yet, we are not clear if to buyback with all the tax or keep base token also. 1 = spend all base tokens
    "buy_backs_coef": 1,
    "timeframe": 3600
    * 4,  # time difference between 2 price points of inputs in seconds, makes up axis X on charts. tied to steps in 
    *  imulationSamples
    "start_date": datetime.now(),  # start date of axis X
    "swap_pool_coef": 0.475,  # ratio how much of tax goes to the swap pool
    "staking_pool_coef": 0.475,  # ratio how much of tax goes to the staking pool
    "oracle_pool_coef": 0.025,  # ratio how much of tax goes to the oracle pool
    "community_pool_coef": 0.025,  # ratio how much of tax goes to the community pool
    # soft peg related increase variables
    "soft_peg_increase": 0.1,  # how much is softpeg raised in 1 step
    "soft_peg_moving_window": 10,  # moving average window length used for price
}
3. run sim for each of the price functions and display results
for sim in sims:
    # we do a deep copy to start each simulation with original market state
    # use_market = copy.deepcopy(mkt)
    base = MarketQuote(base_pair, ust_start_price)
    quote = MarketQuote(quote_pair, 1)
    mkt = new_market(liquidity_usd, quote, base, binance_swap_fee)

    # run first with buybacks
    use_args = copy.deepcopy(div_protocol_args)
    use_args["do_buybacks"] = True
    amm = ConstantProductEngine(mkt)
    div_strategy = DivStrategy(amm, use_args) # instantiate div strategy class
    simul = peg_simulation(sims[sim], div_strategy, use_args, "avg") # run the simulation, returned are trades with all data

    # now run without buybacks, this is optional, if you want to overlay in1 chart ust price with and without buybacks
    use_args = copy.deepcopy(div_protocol_args)
    use_args["do_buybacks"] = False
    amm = ConstantProductEngine(mkt)
    div_strategy = DivStrategy(amm, use_args)
    simul_nobuyback = peg_simulation(sims[sim], div_strategy, use_args, "avg")

    # add no buyback price to the simulation
    simul["breakdown"]["mkt_price_nbb"] = simul_nobuyback["breakdown"].mkt_price

    simul["sim_name"] = sim
    # display results
    show(new_simulation_figure(mkt, simul))

**Comment by Kyjaque** [comment]
## Inner logic
### peg_simulation

**Comment by Kyjaque** [comment]
closing cause of future code reset from faffy

**Pull request closed without merging**
